### ISSUE TITLE
gdal.dll no longer versioned

### ISSUE THREAD

**Issue by Chronial** [cgohlke/geospatial-wheels#1]
First of all, thanks a lot for providing these pre-build wheels ❤️.

I noticed a difference in these wheels compared to [your old builds](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal): The name of the included gdal dll changed from `gdal_<version_number>.dll` to `gdal.dll`.

This is an issue for our use-case: We load python and the gdal wheel into a bigger application, which itself also uses a (possibly different) version of gdal. In general, the old variant seems safer – even in a normal python environment there might be some other gdal version another package wants to load.

Is this change intentional / is there any chance of the gdal dll name becoming versioned again?

**Comment by cgohlke** [comment]
The issue likely is due to GDAL switching to a CMake build system. Please report GDAL specific issues at https://github.com/OSGeo/gdal/issues.
